### REGISTRAR USUARIO
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "nombre": "Celeste",
  "email": "celeste@utn.com",
  "password": "1234"
}

###

### LOGIN
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "celeste@utn.com",
  "password": "1234"
}
