### LISTAR USUARIOS
GET http://localhost:3000/usuarios
Authorization: Bearer TU_TOKEN_AQUI

### CREAR USUARIO MANUALMENTE
POST http://localhost:3000/usuarios
Authorization: Bearer TU_TOKEN_AQUI
Content-Type: application/json

{
"nombre": "NuevoUsuario",
"email": "nuevo@utn.edu",
"password": "abc123"
}
